apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - loki.yaml
  - tempo.yaml
  - mimir.yaml
  - grafana.yaml
  - promtail.yaml
  - prometheus.yaml
  - otel-collector.yaml
